import {
  BarChart3,
  Blocks,
  Camera,
  CheckCircle2,
  ClipboardList,
  Factory,
  Gem,
  Headphones,
  LayoutDashboard,
  MapPin,
  Navigation,
  Package,
  RefreshCw,
  Rocket,
  Route,
  ShoppingCart,
  Smartphone,
  Store,
  TrendingUp,
  Truck,
  Users,
  UsersRound,
  Utensils,
  Wifi,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  "refresh-cw": RefreshCw,
  route: Route,
  "map-pin": MapPin,
  "shopping-cart": ShoppingCart,
  camera: Camera,
  "check-circle-2": CheckCircle2,
  users: Users,
  package: Package,
  "clipboard-list": ClipboardList,
  truck: Truck,
  factory: Factory,
  store: Store,
  "users-round": UsersRound,
  utensils: Utensils,
  "bar-chart-3": BarChart3,
  smartphone: Smartphone,
  wifi: Wifi,
  blocks: Blocks,
  navigation: Navigation,
  rocket: Rocket,
  "layout-dashboard": LayoutDashboard,
  "trending-up": TrendingUp,
  headphones: Headphones,
  gem: Gem,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
